### ISSUE TITLE
Define a clear theme for the course

### ISSUE THREAD

**Issue by docsteveharris** [datascibc/course#14]
- [x] ideas from @tompollard 
- [ ] ideas from @ngageorange 
- [ ] ideas from @dannyjnwong 
- [ ] ideas from @mn936148 
- [ ] ideas from @finncatling 
- [ ] ideas from Rui
- [ ] ideas from @docsteveharris

Please add your notes at https://github.com/datascibc/course/wiki/course-theme

**Comment by tompollard** [comment]
Do you have more information on what data will be available or is this undecided?

**Comment by docsteveharris** [comment]
Undecided. Be keen to have some 'dirty' data from a spreadsheet to show 
people how to clean this up + some other clinical stuff.

**Comment by dannyjnwong** [comment]
In terms of what data to use, there's a large repository of open NHS outcomes data that the HSCIC maintains that we could use: https://indicators.ic.nhs.uk/webview/

**Comment by dannyjnwong** [comment]
Keen that we get the participants to produce some great visualisation. I know what got me excited was making a great picture!

**Comment by mn936148** [comment]
There's also a lot of free data available on NHS England stats page (https://www.england.nhs.uk/statistics/statistical-work-areas/)

In terms of theme, I like the idea a controversial topic in critical care: I think at the meeting someone suggested fluid responsiveness as a good one
