### ISSUE TITLE
Curriculum mapping

### ISSUE THREAD

**Issue by docsteveharris** [datascibc/course#16]
- [ ] ideas from @ngageorange 
- [x] ideas from @dannyjnwong  (RCOA stuff)
- [ ] ideas from @mn936148  (ACCS stuff)
- [x] ideas from @finncatling (FP stuff)
- [ ] ideas from Rui (Nursing and AHP)
- [x] ideas from @docsteveharris (FICM)

Please add your notes at https://github.com/datascibc/course/wiki/educational-credit

**Comment by dannyjnwong** [comment]
In terms of what data to use, there's a large repository of open NHS outcomes data that the HSCIC maintains that we could use: https://indicators.ic.nhs.uk/webview/

**Comment by dannyjnwong** [comment]
Sorry I should've put that in the other issue page.

**Comment by docsteveharris** [comment]
@finncatling awesome - thanks. My bad for not having done the FICM stuff. Will do this week

**Comment by dannyjnwong** [comment]
I have made additions to the curriculum from the FRCA syllabus

**Comment by docsteveharris** [comment]
Thanks Danny - very helpful

**Comment by ngageorange** [comment]
I've had a look at FRCA Curriculums Annex B, C & D - for basic, intermediate and higher training and they don't provide any new ideas above Annex G.
Thanks @dannyjnwong for doing the FRCA Annex G stuff...

**Comment by docsteveharris** [comment]
done FICM - there seems to be potential theme here that would allow us to target the QI audience
