### ISSUE TITLE
Confirm potential date

### ISSUE THREAD

**Issue by docsteveharris** [datascibc/course#27]

**Comment by docsteveharris** [comment]
Propose 14 May Sat
Check does not clash with exams

- MRCP
- FRCA
- FFICM

**Comment by finncatling** [comment]
2016 MRCP dates to avoid:

- Part 1 on 10/5/16 and 6/9/16
- Part 2 on 29-30/6/16 and 7-8/12/16
- No PACES exams happen from 28/3/16 - 3/6/16 and 8/8/16 - 30/9/16

**Comment by dannyjnwong** [comment]
Primary FRCA OSCE/Viva week starts on May  16th
