### ISSUE TITLE
Look into R notebook

### ISSUE THREAD

**Issue by docsteveharris** [datascibc/course#30]

**Comment by finncatling** [comment]
This seems very simple and is well-supported by GitHub. [This](https://try.jupyter.org/) (click on 'Welcome R - demo) shows a simple example of what a finished notebook might look like.

To write/run notebooks locally:
- [Install](http://jupyter.readthedocs.org/en/latest/install.html) iPython notebook (+ Python if you don't already have it)
- [Install](http://irkernel.github.io/installation/) the R kernel for Jupyter
-  [Run the notebook](http://jupyter.readthedocs.org/en/latest/running.html) (opens in web browser)

Haven't tested getting notebooks on GitHub myself but [apparently](https://github.com/blog/1995-github-jupyter-notebooks-3) it as simple as commiting a .ipynb file to a new or existing repository. It all works from the cloud so no need for our course attendees to have anything special installed to view/edit/run the notebook.

**Comment by docsteveharris** [comment]
@finncatling thanks for looking into this. added your notes as a wiki page as I think we will want to  reference this 
See https://github.com/datascibc/course/wiki/Jupyter-notebooks-for-R

**Comment by tompollard** [comment]
> It all works from the cloud so no need for our course attendees to have anything special installed to view/edit/run the notebook.

Although GitHub displays the content of a Jupyter Notebook nicely, it doesn't let you run them. e.g. see: https://github.com/MIT-LCP/mimic-workshop/blob/master/intro_to_mimic/01-example-patient-heart-failure.ipynb

Binder allows you to create web executable Notebooks in the way you suggest: http://mybinder.org/. It's not reliable enough for a workshop unfortunately, but could possibly serve as a backup plan (/last resort!).

**Comment by finncatling** [comment]
Oops sorry Tom - you're correct :)

**Comment by tompollard** [comment]
Getting participants set up with software at the start of these workshops is always a bit painful, but I think the time is well spent because (hopefully!) they'll want to use it again in the future. We try to avoid reliance on the web too because it usually turns out to be flaky :)
